# this source code form is subject to the terms of the mozilla public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

## ------------------------------------------- Plugin enable properties ------------------------------------------------------------
mosip.certify.integration.scan-base-package=io.mosip.certify.postgresdataprovider.integration
mosip.certify.integration.audit-plugin=LoggerAuditService
mosip.certify.plugin-mode=DataProvider
mosip.certify.integration.data-provider-plugin=PostgresDataProviderPlugin

## --------------------------------------------DataProvider specific Certify configuration ---------------------------------------------------
# set custom VC expiry, supports limited subset of ISO-8601 Duration format starting from days to seconds
# E.g. P21dT1h-2m3s for more information check javadoc of Duration.parse(String)
mosip.certify.data-provider-plugin.vc-expiry-duration:P730d
# Cache-Control max-age value for rendering templates
mosip.certify.rendering-template.cache-max-age-days=1


## ------------------------------------------- Plugin specific usecase properties ------------------------------------------------------------
## Postgres DB specific config
# optional field to specify VC signature algo for CertifyIssuer, defaults to Ed25519Signature2020
mosip.certify.status-list.signature-crypto-suite=Ed25519Signature2020
mosip.certify.data-provider-plugin.did-url=did:web:inji.github.io:inji-config:collab:university
mosip.certify.issuer.svg.template.id=
# Setting this property will add `id` attribute to the credential which will be persisted in the ledger table as `credentialId` for the issued credentials.
mosip.certify.data-provider-plugin.id-field-prefix-uri=
# maps OpenID scope to the DB query string where :id is fetched from the token's "sub" field
mosip.certify.data-provider-plugin.postgres.scope-query-mapping={\
    'university_vc_ldp': 'select * from students where id=:id'\
  }

## ------------------------------------------- Authorization usecase properties ------------------------------------------------------------

mosip.certify.authn.allowed-audiences={ '${mosip.certify.domain.url}${server.servlet.path}/issuance/credential', '${mosip.certify.authorization.url}/v1/esignet/vci/credential', 'http://localhost:8088/v1/certify/issuance/credential', 'account'}


## ------------------------------------------- UseCase specific default overriding properties ------------------------------------------------------------
mosip.certify.domain.url=https://${mosip.injicertify.university.host:${mosip.injicertify.host}}
mosip.certify.identifier=${mosip.certify.domain.url}
# E.g https://keycloak-26.dev2.mosip.net/auth/realms/inji 
mosip.certify.authorization.url=${mosip.keycloak.authorization.uri}
mosip.certify.authn.issuer-uri=${mosip.certify.authorization.url}
mosip.certify.authn.jwk-set-uri=${mosip.certify.authorization.url}/protocol/openid-connect/certs
mosip.certify.database.name=inji_certify_university
## softhsm pin
mosip.kernel.keymanager.hsm.keystore-pass=${softhsm.certify.academic.security.pin:${softhsm.certify.security.pin}}
# Set the key prefix for Redis cache
mosip.certify.cache.redis.key-prefix=${mosip.injicertify.university.host}::
# Issuer display property for credential configuration well-known
mosip.certify.credential-config.issuer.display={\
  {\
    'name': 'Acme University',\
    'locale': 'en'\
    'logo':{'url':'https://inji.github.io/inji-config/logos/mosipid-logo.png',\
         'alt_text':'mosip-logo'}\
  }\
}